In [11]:
import numpy as np

In [12]:
import mcubes

In [13]:
X, Y, Z = np.mgrid[0:30, 0:30, 0:30]

In [14]:
u = (X-15)**2 + (Y-15)**2 + (Z-15)**2 - 8**2

In [15]:
vertices, triangles = mcubes.marching_cubes(u, 0)

In [16]:
mcubes.export_mesh(vertices, triangles, "sphere.dae", "MySphere")

In [19]:
print(u)

[[[611 582 555 ... 530 555 582]
  [582 553 526 ... 501 526 553]
  [555 526 499 ... 474 499 526]
  ...
  [530 501 474 ... 449 474 501]
  [555 526 499 ... 474 499 526]
  [582 553 526 ... 501 526 553]]

 [[582 553 526 ... 501 526 553]
  [553 524 497 ... 472 497 524]
  [526 497 470 ... 445 470 497]
  ...
  [501 472 445 ... 420 445 472]
  [526 497 470 ... 445 470 497]
  [553 524 497 ... 472 497 524]]

 [[555 526 499 ... 474 499 526]
  [526 497 470 ... 445 470 497]
  [499 470 443 ... 418 443 470]
  ...
  [474 445 418 ... 393 418 445]
  [499 470 443 ... 418 443 470]
  [526 497 470 ... 445 470 497]]

 ...

 [[530 501 474 ... 449 474 501]
  [501 472 445 ... 420 445 472]
  [474 445 418 ... 393 418 445]
  ...
  [449 420 393 ... 368 393 420]
  [474 445 418 ... 393 418 445]
  [501 472 445 ... 420 445 472]]

 [[555 526 499 ... 474 499 526]
  [526 497 470 ... 445 470 497]
  [499 470 443 ... 418 443 470]
  ...
  [474 445 418 ... 393 418 445]
  [499 470 443 ... 418 443 470]
  [526 497 470 ... 445 470 4

In [ ]:
import numpy as np

In [20]:
import mcubes

In [23]:
x, y, z = np.mgrid[:100, :100, :100]
binary_sphere = (x - 50)**2 + (y - 50)**2 + (z - 50)**2 - 25**2 < 0

# Extract the 0.5-levelset since the array is binary
vertices, triangles = mcubes.marching_cubes(binary_sphere, 0.5)

In [24]:
vertices, triangles = mcubes.marching_cubes(binary_sphere, 0.5)

In [25]:
mcubes.export_obj(vertices, triangles, 'sphere.obj')